config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/update'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/index'
  get 'categories/show'
  get 'books/new'
  get 'books/create'
  get 'books/update'
  get 'books/edit'
  get 'books/destroy'
  get 'books/index'
  get 'books/show'
  get 'about/index'

  get 'about' => 'about#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "books#index"

  resources :books
  resources :authors
  resources :categories
  resources :publishers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books

	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :category
    belongs_to :author
    belongs_to :publisher
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books

    validates :name, presence: true, length:{minimum:3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books

	validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = "About Us";
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save  
      flash[:notice] = "Author Created"

      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])

    @author.update(author_params)

    flash[:notice] = 'Author Updated'

    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])

    @author.destroy

    flash[:notice] = 'Author Removed'

    redirect_to authors_path
  end

  def index
    @authors = Author.all
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add New Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    @book.save

    flash[:notice] = 'Book Added'

    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])

    @book.update(book_params)

    flash[:notice] = 'Book Updated'

    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])

    @book.destroy

    flash[:notice] = 'Book Removed'

    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
    def book_params
    params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year, :coverpath)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save  
      flash[:notice] = "Category Created"

      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    @category.update(category_params)

    flash[:notice] = 'Category Updated'

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy

    flash[:notice] = 'Category Removed'

    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books =  @category.books
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher .save  
      flash[:notice] = "Publisher Created"

      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])

    @publisher.update(publisher_params)

    flash[:notice] = 'Publisher Updated'

    redirect_to publishers_path
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])

    @publisher.destroy

    flash[:notice] = 'Publisher Removed'

    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all
  end

  private
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.slim
h1= @page_title

p Find me in app/views/about/index.html.slim

app/views/authors/create.html.slim
h1 Authors#create
p Find me in app/views/authors/create.html.slim

app/views/authors/destroy.html.slim
h1 Authors#destroy
p Find me in app/views/authors/destroy.html.slim

app/views/authors/edit.html.slim
h2 Edit Author
= form_for @author do |f|
  /! Check for errors
  - if @author.errors.any?
    - @author.errors.full_messages.each do |msg|
      /! Show errors
      .alert.alert-danger= msg
  .form-group
    = f.label :first_name
    br/
    = f.text_field :first_name, class:'form-control'
    br/
  .form-group
    = f.label :last_name
    br/
    = f.text_field :last_name, class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", authors_path, class:'btn btn-default'

app/views/authors/index.html.slim
h2 Authors
table.table.table-striped
  tr
    th Author Name
    th Actions
  - @authors.each do |author|
    tr
      td
        = author.first_name
        = author.last_name
      td
        = link_to 'Edit', edit_author_path(author.id)
        | | #{link_to 'Delete', author_path(author), method: :delete, data: {confirm: 'Are you sure?'}}

app/views/authors/new.html.slim
h2 Add New Author
= form_for @author do |f|
  /! Check for errors
  - if @author.errors.any?
    - @author.errors.full_messages.each do |msg|
      /! Show errors
      .alert.alert-danger= msg
  .form-group
    = f.label :first_name
    br/
    = f.text_field :first_name, class:'form-control'
    br/
  .form-group
    = f.label :last_name
    br/
    = f.text_field :last_name, class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", authors_path, class:'btn btn-default'

app/views/authors/show.html.slim
h1 Authors#show
p Find me in app/views/authors/show.html.slim

app/views/authors/update.html.slim
h1 Authors#update
p Find me in app/views/authors/update.html.slim

app/views/books/create.html.slim
h1 Books#create
p Find me in app/views/books/create.html.slim

app/views/books/destroy.html.slim
h1 Books#destroy
p Find me in app/views/books/destroy.html.slim

app/views/books/edit.html.slim
h2 Edit Book
= form_for @book do |f|
  .form-group
    = f.label :title
    br/
    = f.text_field :title, class:'form-control'
    br/
  .form-group
    = f.label :isbn
    br/
    = f.text_field :isbn ,class:'form-control'
    br/
  .form-group
    = f.label :category
    br/
    = f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control'
    br/
    br/
  .form-group
    = f.label :author
    br/
    = f.select :author_id, Author.all.collect {|x| [x.first_name + ' '+ x.last_name, x.id]}, {:include_blank => 'Select One'},class:'form-control'
    br/
    br/
  .form-group
    = f.label :publisher
    br/
    = f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control'
    br/
    br/
  .form-group
    = f.label :format
    br/
    = f.text_field :format ,class:'form-control'
    br/
  .form-group
    = f.label :year
    br/
    = f.text_field :year ,class:'form-control'
    br/
  .form-group
    = f.label :coverpath
    br/
    = f.text_field :coverpath ,class:'form-control'
    br/
  .form-group
    = f.label :excerpt
    br/
    = f.text_area :excerpt ,class:'form-control'
    br/
  .form-group
    = f.label :pages
    br/
    = f.number_field :pages ,class:'form-control'
    br/
  .form-group
    = f.label :price
    br/
    = f.text_field :price ,class:'form-control'
    br/
  .form-group
    = f.label :buy
    br/
    = f.text_field :buy ,class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", books_path, class:'btn btn-default'

app/views/books/index.html.slim
#books-index
  - @books.each_slice(4) do |book|
    .row
      - book.each do |book|
        .col-md-3.col-sm-3
          h3= book.title
          = image_tag(book.coverpath)
          = link_to 'Read More', book_path(book), class:'btn btn-primary'

app/views/books/new.html.slim
h2 Add New Book
= form_for @book do |f|
  .form-group
    = f.label :title
    br/
    = f.text_field :title, class:'form-control'
    br/
  .form-group
    = f.label :isbn
    br/
    = f.text_field :isbn ,class:'form-control'
    br/
  .form-group
    = f.label :category
    br/
    = f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control'
    br/
    br/
  .form-group
    = f.label :author
    br/
    = f.select :author_id, Author.all.collect {|x| [x.first_name + ' '+ x.last_name, x.id]}, {:include_blank => 'Select One'},class:'form-control'
    br/
    br/
  .form-group
    = f.label :publisher
    br/
    = f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control'
    br/
    br/
  .form-group
    = f.label :format
    br/
    = f.text_field :format ,class:'form-control'
    br/
  .form-group
    = f.label :year
    br/
    = f.text_field :year ,class:'form-control'
    br/
  .form-group
    = f.label :coverpath
    br/
    = f.text_field :coverpath ,class:'form-control'
    br/
  .form-group
    = f.label :excerpt
    br/
    = f.text_area :excerpt ,class:'form-control'
    br/
  .form-group
    = f.label :pages
    br/
    = f.number_field :pages ,class:'form-control'
    br/
  .form-group
    = f.label :price
    br/
    = f.text_field :price ,class:'form-control'
    br/
  .form-group
    = f.label :buy
    br/
    = f.text_field :buy ,class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", books_path, class:'btn btn-default'

app/views/books/show.html.slim
#books-show
  h2= @book.title
  .books-show-left
    = image_tag(@book.coverpath)
  .books-show-right
    h3 Book info:
    ul
      li
        strong Category:
        = @book.category.name
      li
        strong Author:
        = @book.author.first_name
        = @book.author.last_name
      li
        strong Publisher:
        = @book.publisher.name
      li
        strong Year:
        = @book.year
      li
        strong ISBN:
        = @book.isbn
      li
        strong Format:
        = @book.format
      li
        strong Pages:
        = @book.pages
    = link_to "Buy For "+@book.price, @book.buy, class:'btn btn-success',target:'_blank'
  .clearfix
  h4 Excerpt
  p= @book.excerpt
  h3 Admin Functions
  = link_to 'Edit', edit_book_path(@book.id)
  | | #{link_to 'Delete', book_path(@book), method: :delete, data: {confirm: 'Are you sure?'}}

app/views/books/update.html.slim
h1 Books#update
p Find me in app/views/books/update.html.slim

app/views/categories/create.html.slim
h1 Categories#create
p Find me in app/views/categories/create.html.slim

app/views/categories/destroy.html.slim
h1 Categories#destroy
p Find me in app/views/categories/destroy.html.slim

app/views/categories/edit.html.slim
h2 Edit Category
= form_for @category do |f|
  /! Check for errors
  - if @category.errors.any?
    - @category.errors.full_messages.each do |msg|
      /! Show errors
      .alert.alert-danger= msg
  .form-group
    = f.label :name
    br/
    = f.text_field :name, class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", categories_path, class:'btn btn-default'

app/views/categories/index.html.slim
h2 Categories
table.table.table-striped
  tr
    th Category Name
    th Actions
  - @categories.each do |category|
    tr
      td= category.name
      td
        = link_to 'Edit', edit_category_path(category.id)
        | | #{link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?'}}

app/views/categories/new.html.slim
h2 Add New Category
= form_for @category do |f|
  /! Check for errors
  - if @category.errors.any?
    - @category.errors.full_messages.each do |msg|
      /! Show errors
      .alert.alert-danger= msg
  .form-group
    = f.label :name
    br/
    = f.text_field :name, class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", categories_path, class:'btn btn-default'

app/views/categories/show.html.slim
h2= @category.name
#books-index
  - @books.each_slice(4) do |book|
    .row
      - book.each do |book|
        .col-md-3.col-sm-3
          h3= book.title
          = image_tag(book.coverpath)
          = link_to 'Read More', book_path(book), class:'btn btn-primary'

app/views/categories/update.html.slim
h1 Categories#update
p Find me in app/views/categories/update.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      = @page_title ? @page_title : 'Welcome'
      | | The BookStore
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .navbar.navbar-default.navbar-fixed-top role="navigation" 
      .container
        .navbar-header
          button.navbar-toggle.collapsed data-target=".navbar-collapse" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li class=("#{params[:controller] == 'books' ? 'active' : ''}") = link_to 'Home', root_path
            li class=("#{params[:controller] == 'about' ? 'active' : ''}") = link_to 'About', about_path
          ul.nav.navbar-nav.navbar-right
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#" 
                | Add New
                span.caret
              ul.dropdown-menu.navbar-right role="menu" 
                li= link_to "Book", new_book_path
                li= link_to "Category", new_category_path
                li= link_to "Author", new_author_path
                li= link_to "Publisher", new_publisher_path
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#" 
                | Manage
                span.caret
              ul.dropdown-menu.navbar-right role="menu" 
                li= link_to "Categories", categories_path
                li= link_to "Authors", authors_path
                li= link_to "Publishers", publishers_path
        /! /.nav-collapse
    header
      .container
        h1
          | The BookStore
          small= @page_title ? @page_title : 'Welcome'
    section
      .container
        .row
          .col-md-8
            /! Alerts & Messages
            - if flash[:notice]
              .alert.alert-success= flash[:notice]
            - if flash[:alert]
              .alert.alert-danger= flash[:alert]
            = yield
          .col-md-4
            = render 'partials/sidebar'
    footer
      .container
        p Copyright © 2014, All Rights Reserved

app/views/partials/_sidebar.html.slim
- if params[:controller] == 'about'
  .well
    h3 Location Info
    ul
      li The BookStore
      li 499 Massachusetts Ave, Unit 2
      li Boston, MA 02110
      li Phone: (617) 555-5555
      li Email: support@thebookstore.com
- if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show'
  .list-group
    - @categories.each do |category|
      = link_to category.name, category_path(category.id), class:'list-group-item'

app/views/publishers/create.html.slim
h1 Publishers#create
p Find me in app/views/publishers/create.html.slim

app/views/publishers/destroy.html.slim
h1 Publishers#destroy
p Find me in app/views/publishers/destroy.html.slim

app/views/publishers/edit.html.slim
h2 Edit Publisher
= form_for @publisher do |f|
  /! Check for errors
  - if @publisher.errors.any?
    - @publisher.errors.full_messages.each do |msg|
      /! Show errors
      .alert.alert-danger= msg
  .form-group
    = f.label :name
    br/
    = f.text_field :name, class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", publishers_path, class:'btn btn-default'

app/views/publishers/index.html.slim
h2 Publishers
table.table.table-striped
  tr
    th Publisher Name
    th Actions
  - @publishers.each do |publisher|
    tr
      td= publisher.name
      td
        = link_to 'Edit', edit_publisher_path(publisher.id)
        | | #{link_to 'Delete', publisher_path(publisher), method: :delete, data: {confirm: 'Are you sure?'}}

app/views/publishers/new.html.slim
h2 Add New Publisher
= form_for @publisher do |f|
  /! Check for errors
  - if @publisher.errors.any?
    - @publisher.errors.full_messages.each do |msg|
      /! Show errors
      .alert.alert-danger= msg
  .form-group
    = f.label :name
    br/
    = f.text_field :name, class:'form-control'
    br/
  = f.submit "Submit", class:'btn btn-primary'
  = link_to "Cancel", publishers_path, class:'btn btn-default'

app/views/publishers/show.html.slim
h1 Publishers#show
p Find me in app/views/publishers/show.html.slim

app/views/publishers/update.html.slim
h1 Publishers#update
p Find me in app/views/publishers/update.html.slim